### ISSUE TITLE
More time for success?

### ISSUE THREAD

**Issue by codewinch** [mholt/acmez#5]
In https://github.com/mholt/acmez/blob/master/client.go#L114 , does that mean that it will only wait 1 second for LetsEncrypt to respond?

We have sometimes waited for 10 or 20 seconds. :( Can we send a pull request to change that one line, or am I misunderstanding that line?

Thanks for an awesome lib!

**Comment by mholt** [comment]
No, that line just waits 1 second between retries.

FYI, most Go programmers will actually want to use [CertMagic](https://github.com/caddyserver/certmagic) to automate certificates because this library does not keep them renewed (and since certificates expire, simply getting them without renewing them is not very useful).
